// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod"

export const zUser = z.object({
  id: z.string().uuid(),
  username: z.string().min(3).max(32),
  email: z.string().max(64),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const zUserRegistration = z.object({
  username: z
    .string()
    .min(3)
    .max(32)
    .regex(/^[A-Za-z][A-Za-z0-9_]*$/),
  email: z.string().email().min(1).max(64),
  password: z
    .string()
    .min(6)
    .max(64)
    .regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$/),
})

export const zAuthTokens = z.object({
  accessToken: z.string(),
})

export const zLoginCredentials = z.object({
  username: z.string().min(1),
  password: z.string().min(1),
})

export const zNote = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  title: z.union([z.string().max(256), z.null()]),
  content: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const zNoteCreate = z.object({
  title: z.string().max(256).optional(),
  content: z.string().min(1),
})

export const zNotePatch = z.object({
  title: z.string().max(256).optional(),
  content: z.string().optional(),
})

export const zRegisterData = z.object({
  body: zUserRegistration.optional(),
  path: z.never().optional(),
  query: z.never().optional(),
})

/**
 * User created successfully
 */
export const zRegisterResponse = zUser

export const zLoginData = z.object({
  body: zLoginCredentials.optional(),
  path: z.never().optional(),
  query: z.never().optional(),
})

/**
 * Login successful
 */
export const zLoginResponse = zAuthTokens

export const zListNotesData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
})

/**
 * List of notes
 */
export const zListNotesResponse = z.array(zNote)

export const zCreateNoteData = z.object({
  body: zNoteCreate.optional(),
  path: z.never().optional(),
  query: z.never().optional(),
})

/**
 * Note created successfully
 */
export const zCreateNoteResponse = zNote

export const zDeleteNoteData = z.object({
  body: z.never().optional(),
  path: z.object({
    noteId: z.string().uuid(),
  }),
  query: z.never().optional(),
})

/**
 * Note deleted successfully
 */
export const zDeleteNoteResponse = z.void()

export const zGetNoteByIdData = z.object({
  body: z.never().optional(),
  path: z.object({
    noteId: z.string().uuid(),
  }),
  query: z.never().optional(),
})

/**
 * Note details
 */
export const zGetNoteByIdResponse = zNote

export const zPatchNoteData = z.object({
  body: zNotePatch.optional(),
  path: z.object({
    noteId: z.string().uuid(),
  }),
  query: z.never().optional(),
})

/**
 * Note updated successfully
 */
export const zPatchNoteResponse = zNote

export const zGetCurrentUserData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
})

/**
 * User details
 */
export const zGetCurrentUserResponse = zUser
